global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: meta
    static_configs:
      - targets: ["rw-meta:1250"]

  - job_name: frontend
    static_configs:
      - targets: ["rw-frontend:2222"]

  - job_name: compute
    static_configs:
      - targets: ["rw-compute:1222"]

  - job_name: compactor
    static_configs:
      - targets: ["rw-compactor:1260"]
