data_source analytics:
  type: postgres
  host: ${SODA_POSTGRES_HOST}
  port: ${SODA_POSTGRES_PORT}
  username: ${SODA_POSTGRES_USERNAME}
  password: ${SODA_POSTGRES_PASSWORD}
  database: ${SODA_POSTGRES_DB}
  schema: silver
